#!/bin/bash

seq 1000 | while read x
do
curl -X GET "http://localhost:4993/environment" 2> /dev/null | tr ',{' '\n' | grep mdl | cut -d ':' -f 2 | tr '\n' '\t' 
curl -X GET "http://localhost:4996/environment" 2> /dev/null | awk -F ':' '{print($9)}' | awk -F ',' '{print($1)}' | tr '\n' '\t'
curl -X GET http://localhost:4998/state/get 2> /dev/null | tr ',' '\n' | grep passed | head -1| cut -d ':' -f 2
sleep 1;
done
